### ISSUE TITLE
Wrong region in Game name for Mario Kart 64

### ISSUE THREAD

**Issue by ottelo9** [bryc/mpkedit#21]
I played Mario Kart 64 (E) via SummerCart64 and saved ghost data to my memory pak (BlueRetro bank1). This is what [MPKEdit](https://bryc.github.io/mpkedit/) shows:

![image](https://github.com/user-attachments/assets/a78588f5-fbbb-4bdb-9904-cb188fb456f6)

**Comment by bryc** [comment]
Yeah... all versions of MK64 use the `NKTJ` gameCode in the ghost-saving Controller Pak code. They didn't bother to change it when localizing the game in English. And if the region is changed manually on the C-Pak, it won't find the ghost data because it's specifically looking for `NKTJ`.

The region of save files aren't actually visible in official C-Pak menus (as region-free was never a thing), so I assume it was an unimportant detail.

**Comment by ottelo9** [comment]
Thanks for the Informations :)
